import pandas as pd
import pandas_ta as ta
import yfinance as yf

# Define your parameters
FAST_EMA = 9
SLOW_EMA = 21
VOLUME_MA_PERIOD = 20
VOLUME_MULTIPLIER = 2.5

# Define the watchlist (NSE stocks via Yahoo Finance syntax)
watchlist = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "TATASTEEL.NS"]

def check_breakout(ticker):
    try:
        # FIXED: Using yf.Ticker().history() to avoid MultiIndex errors
        stock = yf.Ticker(ticker)
        df = stock.history(period="6mo")
        
        if df.empty:
            return None
            
        # Calculate Technical Indicators using pandas_ta
        df.ta.ema(length=FAST_EMA, append=True)
        df.ta.ema(length=SLOW_EMA, append=True)
        
        # Calculate the Moving Average of Volume
        df['Vol_MA'] = df['Volume'].rolling(window=VOLUME_MA_PERIOD).mean()
        
        # Drop rows with NaN values generated by moving averages
        df.dropna(inplace=True)
        
        # Get the last two days of data to check for a crossover
        today = df.iloc[-1]
        yesterday = df.iloc[-2]
        
        # Condition 1: EMA Crossover (Fast crossed above Slow today)
        ema_crossover = (yesterday[f'EMA_{FAST_EMA}'] <= yesterday[f'EMA_{SLOW_EMA}']) and \
                        (today[f'EMA_{FAST_EMA}'] > today[f'EMA_{SLOW_EMA}'])
                        
        # Condition 2: Volume Breakout
        volume_breakout = today['Volume'] > (today['Vol_MA'] * VOLUME_MULTIPLIER)
        
        if ema_crossover and volume_breakout:
            return {
                "Ticker": ticker,
                "Close": today['Close'],
                "Volume": today['Volume'],
                "Vol_MA": today['Vol_MA']
            }
    except Exception as e:
        print(f"Error processing {ticker}: {e}")
    
    return None

# Run the screener
print("Running Screener...")
breakout_stocks = []

for symbol in watchlist:
    result = check_breakout(symbol)
    if result:
        breakout_stocks.append(result)

# Display Results
if breakout_stocks:
    print("\n🚨 Breakouts Detected! 🚨")
    for stock in breakout_stocks:
        print(f"{stock['Ticker']} - Price: {stock['Close']:.2f} | Volume Spike: {stock['Volume'] / stock['Vol_MA']:.1f}x average")
else:
    print("\nNo setups found today.")

